version: '3.1'

services:
  vipekontb-bot:
    depends_on:
      - vipekontb-db
    build:
      context: .
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_DB_USERNAME: ${BOT_DB_USERNAME}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
    restart: always
  vipekontb-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: ${BOT_DB_USERNAME}
      MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
      MYSQL_DATABASE: 'vipekontb_db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    command: --character-set-server=utf8 --collation-server=utf8_general_ci